### ISSUE TITLE
Dataset creating issues

### ISSUE THREAD

**Issue by ShenzheZhu** [adiSimhi/hallucination-mitigation#1]
Got this issue when creating the dataset

`start time 2024-12-17_04:24:33
datasets/ exists
Traceback (most recent call last):
  File "/root/cjiang/info_flow/WACK_CoE/wack/Distinguishing_Ignorance_from_Error_in_LLM_Hallucinations/RunAllSteps.py", line 157, in <module>
    create_dataset(parser.parse_args().dataset_name,
  File "/root/cjiang/info_flow/WACK_CoE/wack/Distinguishing_Ignorance_from_Error_in_LLM_Hallucinations/RunAllSteps.py", line 62, in create_dataset
    hall_save_path = f"{initial_dataset_path}Hallucinate{dataset_name[0].upper() + dataset_name[1:]}WithThreshold{threshold}_{model_name.replace('/', '_')}{ending}"
AttributeError: 'bool' object has no attribute 'replace'`

**Comment by adiSimhi** [comment]
solved in commit 4bc587362239cb4d1d2304258fa4c7be599aa6b4
